version: '3'
services:
  address-service:
    build:
      context: ./address-service
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:5000 app:app
    ports:
      - 5000:5000
    depends_on:
      - db
  # write a code to waif for db to be accepting connections on port 5432
    

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:5001 app:app
    ports:
      - 5001:5001
    depends_on:
      - db

  ngginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - address-service
      - user-service
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres